
spring:
  profiles: dev
  redis:
    database: 0
    host: 192.168.1.134
    port: 6379
    password: 123456
    timeout: 2000
    lettuce:
      pool:
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 40 # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）


---
spring:
  profiles: prod
  redis:
    database: 0
    host: 192.168.1.134
    port: 6379
    password: 123456
    timeout: 200
    lettuce:
      pool:
        min-idle: 5 # 连接池中的最小空闲连接
        max-idle: 40 # 连接池中的最大空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
