spring:
  profiles:
    active: dev
    include: orm,cache
  session:
    store-type: redis

logging:
  file: spring.log
  level:
    root: info
server:
  servlet:
    session:
      timeout: 600

---
spring:
  profiles: dev
  application:
    name: springboot-framework
server:
  port: 10010

---
spring:
  profiles: prod
  application:
    name: springboot-framework
server:
  port: 10010