mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: pers.cj.framework.orm.entity #实体扫描，多个package用逗号或者分号分隔
  global-config:
    id-type: 0 #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    field-strategy: 1 #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    db-column-underline: true #驼峰下划线转换
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    meta-object-handler: pers.cj.framework.orm.config.MyMetaObjectHandler #自定义填充策略接口实现
  configuration:
    map-underscore-to-camel-case: true #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    cache-enabled: false
    jdbc-type-for-null: 'null' #配置JdbcTypeForNull, oracle数据库必须配置
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #打印sql语句,调试用

---
mybatis:
  logic: true  #mybatis-plus是否使用逻辑删除
#数据库连接配置
spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:p6spy:mysql://192.168.1.132:3306/springboot?useInformationSchema=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      #druid WebStatFilter监控配置
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.111
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456



---
mybatis:
  logic: true
#数据库连接配置
spring:
  profiles: prod
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.132:3306/springboot?useInformationSchema=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver



